using System.Text;

namespace IgorSay;

public partial class MainPage : ContentPage
{
  private Dictionary<string, string> termsDictionary;

  private Random random = new Random();

  public MainPage()
  {
    InitializeComponent();
    LoadTerms();
  }


  private async void OnDrawClicked(object sender, EventArgs e)
  {
    DrawButton.IsEnabled = false;

    try
    {
      if (termsDictionary == null || termsDictionary.Count == 0)
      {
        TermLabel.Text = "Brak haseł";
        ExplanationLabel.Text = "Słownik jest pusty.";
        return;
      }

      ExplanationLabel.Text = "";
      TermLabel.Text = "✅ Słowo na dziś ✅";

      List<string> keys = new List<string>(termsDictionary.Keys);
      int boarCount = new Random().Next(3, 10);
      uint animationSpeed = 250;


      await BoarMover.TranslateTo(0, 0, animationSpeed, Easing.SinOut);
      await Task.Delay(300);

      await BoarMover.TranslateTo(-300, 0, animationSpeed, Easing.SinIn);


      for (int i = 0; i < boarCount; i++)
      {

        BoarMover.TranslationX = 300;
        TermLabel.Text = keys[random.Next(keys.Count)];
        await BoarMover.TranslateTo(0, 0, animationSpeed, Easing.SinOut);
        await Task.Delay(50 + (i * 20));
        await BoarMover.TranslateTo(-300, 0, animationSpeed, Easing.SinIn);
      }


      string randomTerm = keys[random.Next(keys.Count)];
      string explanation = termsDictionary[randomTerm];

      BoarMover.TranslationX = 300;
      TermLabel.Text = randomTerm;

      await BoarMover.TranslateTo(0, 0, 400, Easing.BounceOut);

      await AnimateTyping(explanation);
    }
    finally
    {
      DrawButton.IsEnabled = true;
    }
  }


  private async Task AnimateTyping(string text)
  {

    var stringBuilder = new StringBuilder();
    int typingDelay = 25;

    foreach (char c in text)
    {
      stringBuilder.Append(c);
      ExplanationLabel.Text = stringBuilder.ToString();
      await Task.Delay(typingDelay);
    }
  }



  private void LoadTerms()
  {
    termsDictionary = new Dictionary<string, string>
    {
      ["Aksjologia psychologiczna"] = "badanie wartości w zachowaniu i myśleniu człowieka",
      ["Afektywność"] = "zdolność do doświadczania emocji",
      ["Amnezja dysocjacyjna"] = "utrata pamięci związana z traumą lub stresem: nie organicznym uszkodzeniem mózgu",
      ["Anhedonia"] = "brak zdolności do odczuwania przyjemności",
      ["Apatia psychiczna"] = "obniżona motywacja i inicjatywa w działaniu",
      ["Autyzm spektrum"] = "zaburzenia rozwoju wpływające na komunikację: interakcje społeczne i zainteresowania",
      ["Awersja warunkowa"] = "wyuczona reakcja unikania w odpowiedzi na bodziec negatywny",
      ["Behavioralizm (behawioryzm)"] = "nurt psychologiczny skupiający się na obserwowalnych zachowaniach: a nie stanach wewnętrznych",
      ["Cognitywizm"] = "podejście w psychologii koncentrujące się na procesach poznawczych: takich jak myślenie: pamięć: uwaga",
      ["Coping"] = "strategie radzenia sobie ze stresem",
      ["Depersonalizacja"] = "poczucie bycia odłączonym od własnego ciała lub myśli",
      ["Dysocjacja"] = "oddzielenie pewnych procesów psychicznych od świadomości",
      ["Dysonans poznawczy"] = "napięcie psychiczne wynikające z posiadania sprzecznych przekonań lub zachowań",
      ["Ego"] = "w teorii Freuda część osobowości odpowiedzialna za racjonalne działanie",
      ["Egzaltacja"] = "stan nadmiernego pobudzenia emocjonalnego lub intelektualnego",
      ["Emocje afektywne pierwotne"] = "podstawowe emocje: np. strach: radość: gniew",
      ["Empatia poznawcza"] = "zdolność rozumienia uczuć innych osób",
      ["Endofenotyp"] = "wewnętrzny marker biologiczny związany z chorobą psychiczną",
      ["Euforia maniakalna"] = "patologiczny stan podwyższonego nastroju w zaburzeniu afektywnym",
      ["Fenomenologia"] = "badanie doświadczeń subiektywnych jednostki",
      ["Flow"] = "stan całkowitego wczucia się w wykonywaną czynność: związany z optymalną motywacją",
      ["Habituacja"] = "zmniejszenie reakcji na powtarzający się bodziec",
      ["Heurystyki poznawcze"] = "uproszczone strategie myślenia i podejmowania decyzji",
      ["Hipochondria"] = "nadmierne zamartwianie się o własne zdrowie",
      ["Histeria"] = "zaburzenie objawiające się silnymi reakcjami emocjonalnymi i somatycznymi bez organicznej przyczyny",
      ["Id"] = "w teorii Freuda nieświadoma część osobowości dążąca do natychmiastowej gratyfikacji",
      ["Imprinting"] = "proces szybkiego uczenia się specyficznych wzorców zachowania w krytycznym okresie rozwojowym",
      ["Inteligencja emocjonalna"] = "zdolność rozpoznawania: rozumienia i regulowania emocji własnych i innych",
      ["Interakcjonizm symboliczny"] = "teoria socjologiczno-psychologiczna podkreślająca znaczenie symboli i komunikacji w zachowaniu",
      ["Katastrofizacja"] = "myślenie: które przewiduje najgorszy możliwy scenariusz",
      ["Kognitywna dezintegracja"] = "zaburzenie spójności myślenia i percepcji w schizofrenii",
      ["Labilność emocjonalna"] = "częste i szybkie zmiany nastroju",
      ["Lęk uogólniony"] = "przewlekły stan niepokoju bez konkretnej przyczyny",
      ["Mechanizmy obronne"] = "strategie psychiczne chroniące przed lękiem (np. wyparcie: projekcja)",
      ["Neuroplastyczność"] = "zdolność mózgu do reorganizacji i tworzenia nowych połączeń nerwowych",
      ["Neurotyzm"] = "cecha osobowości związana z podatnością na stres i negatywne emocje",
      ["Obsessje"] = "natrętne myśli: które osoba próbuje ignorować lub tłumić",
      ["Paradoks kontroli"] = "zjawisko: w którym nadmierna kontrola prowadzi do utraty kontroli",
      ["Paraliż decyzyjny"] = "niemożność podjęcia decyzji wskutek nadmiaru opcji",
      ["Percepcja subliminalna"] = "przetwarzanie bodźców: które nie docierają do świadomej percepcji",
      ["Perswazja afektywna"] = "wpływ na emocje odbiorcy w celu zmiany jego przekonań lub zachowań",
      ["Personalizacja"] = "przypisywanie sobie odpowiedzialności za zdarzenia niezależne od jednostki",
      ["Placebo"] = "substancja lub interwencja wywołująca efekt dzięki oczekiwaniom pacjenta",
      ["Prawo Yerkesa-Dodsona"] = "zależność między poziomem pobudzenia a wydajnością zadania",
      ["Prokrastynacja"] = "odwlekanie wykonania zadania pomimo świadomości negatywnych konsekwencji",
      ["Projektowanie poznawcze"] = "tworzenie schematów myślowych w odpowiedzi na doświadczenie",
      ["Psychofizjologia"] = "badanie zależności między procesami psychicznymi a funkcjami organizmu",
      ["Psychopatia"] = "zaburzenie osobowości charakteryzujące się brakiem empatii: impulsywnością i manipulacją",
      ["Resiliencia (odporność psychiczna)"] = "zdolność adaptacji do trudnych sytuacji",
      ["Stroop efekt"] = "zjawisko opóźnienia w nazwaniu koloru napisanego słowa: gdy słowo oznacza inny kolor",
      ["Aksjologia"] = "nauka o wartościach; bada: co jest dobre: złe: piękne czy moralnie słuszne",
      ["Epistemologia"] = "teoria poznania; zajmuje się tym: czym jest wiedza i jak ją uzyskujemy",
      ["Metafizyka"] = "dział filozofii zajmujący się tym: co wykracza poza doświadczenie zmysłowe: np. istota bytu: czas: przestrzeń",
      ["Ontologia"] = "nauka o bycie; bada: co istnieje i w jaki sposób istnieje",
      ["Deontologia"] = "etyka obowiązku; określa moralne zasady działania niezależnie od skutków",
      ["Utilitaryzm"] = "teoria etyczna: według której słuszność czynu mierzy się jego skutkiem: zwykle w kategoriach maksymalizacji szczęścia lub dobra",
      ["Dialektyka"] = "metoda dochodzenia do prawdy poprzez dyskusję i zestawienie przeciwstawnych tez",
      ["Nihilizm"] = "pogląd odrzucający obiektywne wartości: sens życia i moralność",
      ["Fenomenologia"] = "kierunek filozoficzny badający strukturę doświadczenia i świadomości: skupiając się na tym: jak rzeczy jawią się człowiekowi",
      ["Egzystencjalizm"] = "nurt filozoficzny koncentrujący się na jednostce: jej wolności i odpowiedzialności w świecie bez wrodzonego sensu",
      ["Stoicyzm"] = "filozofia ucząca panowania nad emocjami i życia zgodnie z rozumem oraz naturą",
      ["Pragmatyzm"] = "kierunek filozoficzny: według którego wartość idei mierzy się ich praktycznym skutkiem",
      ["Determinizm"] = "pogląd: że wszystkie zdarzenia są z góry określone przez przyczyny wcześniejsze: w tym nasze działania",
      ["Solipsyzm"] = "pogląd: że tylko własna świadomość jest pewna: a istnienie innych ludzi i świata zewnętrznego może być wątpliwe",
      ["Transcendencja"] = "to: co wykracza poza doświadczenie i granice zmysłów; często odnoszone do Boga lub absolutu",
      ["Abstrakcja"] = "ukrywanie szczegółów implementacji i eksponowanie tylko istotnych cech obiektu",
      ["Algorytm"] = "skończony zestaw kroków prowadzących do rozwiązania problemu",
      ["API (Application Programming Interface)"] = "zestaw funkcji i procedur pozwalających na komunikację między programami",
      ["Asynchroniczność"] = "wykonywanie operacji niezależnie od głównego wątku programu",
      ["Binarne drzewo"] = "struktura danych: w której każdy węzeł ma maksymalnie dwóch potomków",
      ["Big O Notation"] = "sposób opisu złożoności obliczeniowej algorytmu",
      ["Blokada (Lock)"] = "mechanizm synchronizacji wątków w programowaniu współbieżnym",
      ["Chmura obliczeniowa (Cloud Computing)"] = "udostępnianie zasobów komputerowych przez internet",
      ["Closure"] = "funkcja: która zachowuje dostęp do zmiennych z kontekstu: w którym została stworzona",
      ["Commit"] = "zapisanie zmian w systemie kontroli wersji: np. Git",
      ["Concurrency (współbieżność)"] = "możliwość wykonywania wielu zadań w tym samym czasie",
      ["Containerization"] = "pakowanie aplikacji i jej zależności w izolowane środowisko (np. Docker)",
      ["CRTP (Curiously Recurring Template Pattern)"] = "wzorzec projektowy w C++ używający dziedziczenia szablonów",
      ["Dekorator (Decorator)"] = "wzorzec lub funkcja zmieniająca zachowanie innej funkcji lub klasy",
      ["Dependency Injection"] = "wzorzec: w którym obiekty otrzymują swoje zależności z zewnątrz",
      ["DSL (Domain Specific Language)"] = "język programowania dedykowany określonej dziedzinie",
      ["Encapsulation (enkapsulacja)"] = "ukrywanie danych wewnątrz klasy i udostępnianie ich tylko poprzez metody",
      ["Event Loop"] = "mechanizm w JavaScript obsługujący asynchroniczne zdarzenia",
      ["Garbage Collector"] = "mechanizm automatycznego zwalniania pamięci w niektórych językach programowania",
      ["Generics (szablony)"] = "mechanizm umożliwiający pisanie funkcji i klas działających z różnymi typami danych",
      ["GraphQL"] = "język zapytań do API pozwalający precyzyjnie określić: jakie dane chcemy otrzymać",
      ["Heap (sterta)"] = "obszar pamięci do dynamicznej alokacji obiektów",
      ["Immutable Object"] = "obiekt: którego stan nie może być zmieniony po utworzeniu",
      ["Inheritance (dziedziczenie)"] = "mechanizm pozwalający klasie na odziedziczenie właściwości i metod innej klasy",
      ["Interface"] = "kontrakt: który klasa musi implementować",
      ["IoC (Inversion of Control)"] = "wzorzec: w którym kontrola przepływu programu jest odwrócona",
      ["JSON Web Token (JWT)"] = "standard bezpiecznego przesyłania informacji w formacie JSON",
      ["Lambda"] = "anonimowa funkcja: często wykorzystywana w funkcjach wyższego rzędu",
      ["Lazy Loading"] = "technika opóźnionego ładowania zasobów do momentu ich użycia",
      ["Linked List (lista wiązana)"] = "struktura danych: w której elementy są powiązane wskaźnikami",
      ["Microservices"] = "architektura: w której aplikacja składa się z niezależnych: małych usług",
      ["Monads"] = "abstrakcje w programowaniu funkcyjnym pozwalające na sekwencyjne łączenie operacji",
      ["Multithreading (wielowątkowość)"] = "wykonywanie wielu wątków w ramach jednego procesu",
      ["Mutex"] = "mechanizm zapewniający wzajemne wykluczanie w dostępie do zasobów współdzielonych",
      ["Namespace"] = "przestrzeń nazw zapobiegająca konfliktom nazw w kodzie",
      ["Observer Pattern"] = "wzorzec: w którym obiekty obserwują zmiany stanu innego obiektu",
      ["Polymorphism (polimorfizm)"] = "możliwość traktowania obiektów różnych klas w ten sam sposób",
      ["Queue (kolejka)"] = "struktura danych FIFO (First In: First Out)",
      ["Recursion (rekurencja)"] = "funkcja wywołująca samą siebie",
      ["Refactoring"] = "poprawa struktury kodu bez zmiany jego zachowania",
      ["Regex (wyrażenia regularne)"] = "sposób definiowania wzorców do wyszukiwania w tekstach",
      ["REST API"] = "architektura komunikacji między aplikacjami poprzez protokół HTTP",
      ["Singleton"] = "wzorzec: który pozwala na istnienie tylko jednej instancji klasy",
      ["Stack (stos)"] = "struktura danych LIFO (Last In: First Out)",
      ["Streaming"] = "przetwarzanie danych w strumieniu zamiast w całości",
      ["Template Metaprogramming"] = "technika w C++ pozwalająca wykonywać obliczenia w czasie kompilacji",
      ["Epistemologia"] = "teoria wiedzy",
      ["Ontologia"] = "nauka o bycie",
      ["Aksjologia"] = "teoria wartości",
      ["Fenomenologia"] = "badanie świadomości i doświadczenia",
      ["Dialektyka"] = "metoda dociekań przez przeciwieństwa",
      ["Determinizm"] = "pogląd, że wszystko jest z góry określone",
      ["Egzystencjalizm"] = "filozofia wolności i sensu życia",
      ["Nihilizm"] = "przekonanie o braku obiektywnego sensu",
      ["Pragmatyzm"] = "filozofia praktycznego zastosowania idei",
      ["Stoicyzm"] = "szkoła ucząca panowania nad emocjami",
      ["Hedonizm"] = "cel życia w przyjemności",
      ["Solipsyzm"] = "przekonanie o istnieniu tylko własnej świadomości",
      ["Monizm"] = "rzeczywistość ma jedną podstawową zasadę",
      ["Pluralizm"] = "rzeczywistość składa się z wielu zasad",
      ["Sceptycyzm"] = "wątpliwość wobec możliwości poznania prawdy",
      ["Dogmatyzm"] = "ścisłe trzymanie się założeń bez dowodu",
      ["Dualizm"] = "podział rzeczywistości na dwie odrębne substancje",
      ["Teleologia"] = "wyjaśnianie zjawisk przez ich cel",
      ["Metafizyka"] = "badanie podstaw bytu i rzeczywistości",
      ["Subiektywizm"] = "przekonanie, że wiedza zależy od jednostki",
      ["Algebra"] = "struktury i równania",
      ["Analiza matematyczna"] = "badanie funkcji i granic",
      ["Rachunek różniczkowy"] = "analiza zmian funkcji",
      ["Rachunek całkowy"] = "obliczanie pól, objętości",
      ["Teoria liczb"] = "badanie własności liczb całkowitych",
      ["Kombinatoryka"] = "liczenie sposobów łączenia elementów",
      ["Logarytm"] = "funkcja odwrotna do potęgowania",
      ["Macierz"] = "tablica liczb",
      ["Wektor"] = "obiekt z kierunkiem i długością",
      ["Równanie różniczkowe"] = "zależność między funkcją a jej pochodną",
      ["Fraktal"] = "obiekt o samopodobnej strukturze",
      ["Topologia"] = "badanie własności przestrzeni przy deformacjach",
      ["Hipoteza"] = "przypuszczenie wymagające dowodu",
      ["Twierdzenie"] = "stwierdzenie udowodnione logicznie",
      ["Permutacja"] = "różne ustawienia elementów",
      ["Kombinacja"] = "wybór elementów bez kolejności",
      ["Symetria"] = "własność zachowania przy przekształceniach",
      ["Macierz diagonalna"] = "macierz z wartościami tylko na głównej przekątnej",
      ["Determinant"] = "liczba opisująca macierz",
      ["Równoległobok"] = "czworokąt o równoległych bokach",
      ["Krzywa"] = "linia w przestrzeni",
      ["Prosta"] = "najkrótsza linia między punktami",
      ["Kąt"] = "figura utworzona przez dwie półproste",
      ["Funkcja"] = "przyporządkowanie każdemu elementowi jednego",
      ["Granica"] = "wartość funkcji przy dążeniu argumentu do określonego punktu",
      ["Entropia"] = "miara nieuporządkowania",
      ["Energia kinetyczna"] = "energia ruchu",
      ["Energia potencjalna"] = "energia położenia",
      ["Siła"] = "przyczyna zmiany ruchu",
      ["Moment pędu"] = "ilość ruchu obrotowego",
      ["Kwantyzacja"] = "podział energii na dyskretne jednostki",
      ["Superpozycja"] = "nakładanie stanów kwantowych",
      ["Fale grawitacyjne"] = "zaburzenia czasoprzestrzeni",
      ["Relatywizm"] = "zależność obserwacji od układu odniesienia",
      ["Masa"] = "opór ciała na przyspieszenie",
      ["Prędkość"] = "zmiana położenia w czasie",
      ["Przyspieszenie"] = "zmiana prędkości",
      ["Pole elektromagnetyczne"] = "przestrzeń oddziaływania sił",
      ["Rezonans"] = "wzmocnienie drgań",
      ["Impuls"] = "iloczyn siły i czasu jej działania",
      ["Ciśnienie"] = "siła działająca na jednostkę powierzchni",
      ["Gęstość"] = "masa na jednostkę objętości",
      ["Ciepło"] = "energia przekazywana między ciałami",
      ["Temperatura"] = "miara średniej energii cząsteczek",
      ["Przewodnictwo"] = "zdolność przewodzenia prądu lub ciepła",
      ["Dyfuzja"] = "samoistne rozprzestrzenianie się cząsteczek",
      ["Siła Lorentza"] = "siła działająca na ładunek w polu elektromagnetycznym",
      ["Foton"] = "cząstka światła",
      ["Proton"] = "cząstka dodatnio naładowana w jądrze",
      ["Neutron"] = "cząstka obojętna w jądrze",
      ["Komórka"] = "podstawowa jednostka życia",
      ["DNA"] = "nośnik informacji genetycznej",
      ["RNA"] = "uczestnik syntezy białek",
      ["Gen"] = "odcinek DNA kodujący białko",
      ["Chromosom"] = "struktura DNA w jądrze",
      ["Mitochondrium"] = "elektrownia komórki",
      ["Chloroplast"] = "miejsce fotosyntezy",
      ["Homeostaza"] = "utrzymanie stabilnych warunków",
      ["Apoptoza"] = "programowana śmierć komórki",
      ["Fotosynteza"] = "proces wytwarzania energii ze światła",
      ["Oddychanie komórkowe"] = "proces wytwarzania energii z glukozy",
      ["Enzym"] = "białko przyspieszające reakcje",
      ["Antygen"] = "substancja wywołująca reakcję immunologiczną",
      ["Antyciało"] = "białko neutralizujące antygen",
      ["Mutacja"] = "zmiana w materiale genetycznym",
      ["Ewolucja"] = "proces zmian gatunków",
      ["Selekcja naturalna"] = "mechanizm doboru korzystnych cech",
      ["Symbioza"] = "współżycie dwóch organizmów",
      ["Parazytoza"] = "życie kosztem gospodarza",
      ["Ekosystem"] = "zespół organizmów i środowiska",
      ["Inflacja"] = "wzrost cen towarów i usług",
      ["Deflacja"] = "spadek cen",
      ["Popyt"] = "ilość dóbr, którą chcą kupić konsumenci",
      ["Podaż"] = "ilość dóbr oferowanych na rynku",
      ["PKB"] = "wartość dóbr i usług w kraju",
      ["Recesja"] = "spadek aktywności gospodarczej",
      ["Monopol"] = "rynek z jednym producentem",
      ["Oligopol"] = "rynek z kilkoma producentami",
      ["Kredyt"] = "pożyczka na określony czas",
      ["Kapitał"] = "zasoby finansowe lub rzeczowe",
      ["Dywersyfikacja"] = "rozproszenie inwestycji dla bezpieczeństwa",
      ["Rentowność"] = "stosunek zysków do kosztów",
      ["Amortyzacja"] = "stopniowe rozliczanie kosztów zakupu",
      ["Obligacja"] = "papiery wartościowe z oprocentowaniem",
      ["Akcja"] = "udział w kapitale spółki",
      ["Bilans"] = "zestawienie aktywów i pasywów",
      ["Budżet"] = "plan wydatków i dochodów",
      ["Deficyt"] = "nadwyżka wydatków nad dochodami",
      ["Eksternalność"] = "skutki działań jednostki dla innych",
      ["Inflacja bazowa"] = "inflacja bez cen energii i żywności",
      ["Percepcja"] = "odbiór bodźców zmysłowych",
      ["Kognicja"] = "procesy myślowe i poznawcze",
      ["Motywacja"] = "siła kierująca działaniem",
      ["Emocje"] = "stany psychiczne wywołujące reakcje",
      ["Stres"] = "reakcja organizmu na zagrożenie",
      ["Neuroplastyczność"] = "zdolność mózgu do zmian",
      ["Psychopatologia"] = "nauka o zaburzeniach psychicznych",
      ["Psychoanaliza"] = "metoda badania nieświadomości",
      ["Behaviouralizm"] = "podejście badające zachowanie",
      ["Inteligencja"] = "zdolność rozwiązywania problemów",
      ["Osobowość"] = "zespół cech psychicznych",
      ["Samoocena"] = "ocena własnej wartości",
      ["Awersja"] = "silna niechęć",
      ["Prokrastynacja"] = "odkładanie zadań",
      ["Empatia"] = "zdolność wczuwania się w innych",
      ["Dysocjacja"] = "oddzielenie świadomości od doświadczenia",
      ["Traumatyzm"] = "efekt przeżycia szkodliwego psychicznie",
      ["Mechanizm obronny"] = "strategia radzenia sobie z lękiem",
      ["Konformizm"] = "podporządkowanie się grupie",
      ["Lęk"] = "reakcja na zagrożenie",
      ["Fonetyka"] = "nauka o dźwiękach mowy",
      ["Morfologia"] = "badanie budowy wyrazów",
      ["Semantyka"] = "znaczenie słów i zdań",
      ["Pragmatyka"] = "znaczenie w kontekście użycia",
      ["Syntax"] = "zasady budowy zdań",
      ["Dialekt"] = "lokalna odmiana języka",
      ["Idiom"] = "wyrażenie o znaczeniu niedosłownym",
      ["Etymologia"] = "pochodzenie wyrazów",
      ["Homonim"] = "wyraz o takim samym brzmieniu, innym znaczeniu",
      ["Polisem"] = "wyraz o wielu znaczeniach",
      ["Neologizm"] = "nowo powstałe słowo",
      ["Leksykon"] = "zbiór słów danego języka",
      ["Onomastyka"] = "nauka o nazwach własnych",
      ["Morfem"] = "najmniejsza jednostka znacząca",
      ["Fonem"] = "najmniejsza jednostka dźwiękowa",
      ["Słowotwórstwo"] = "tworzenie nowych wyrazów",
      ["Algorytm"] = "precyzyjna instrukcja rozwiązania problemu",
      ["Baza danych"] = "zbiór uporządkowanych informacji",
      ["Sztuczna inteligencja"] = "systemy imitujące ludzką inteligencję",
      ["Sieć neuronowa"] = "model komputerowy inspirowany mózgiem",
      ["Albowiem"] = "ponieważ, gdyż",
      ["Aczkolwiek"] = "chociaż, mimo że",
      ["Jeno"] = "tylko, jedynie",
      ["Niegdyś"] = "kiedyś, dawniej",
      ["Wszelako"] = "jednak, mimo to",
      ["Uprzednio"] = "wcześniej, przedtem",
      ["Zwierz"] = "zwierzę",
      ["Przeto"] = "dlatego",
      ["Potym"] = "potem, później",
      ["Tudzież"] = "i, oraz",
      ["Bies"] = "demon w wierzeniach ludowych",
      ["Giermek"] = "młody rycerz lub jego pomocnik",
      ["Rycerz"] = "wojownik średniowieczny",
      ["Szlachcic"] = "członek stanu szlacheckiego",
      ["Szeliga"] = "herb szlachecki",
      ["Hufiec"] = "jednostka wojskowa lub harcerska",
      ["Żak"] = "uczeń lub student dawniej",
      ["Knecht"] = "sługa, pachołek",
      ["Świta"] = "towarzystwo króla lub pana",
      ["Dziedzic"] = "właściciel ziemski",
      ["Biesiada"] = "uczta, przyjęcie",
      ["Karafka"] = "naczynie do napojów",
      ["Koryto"] = "misa do karmienia zwierząt lub stół",
      ["Mąka"] = "zboże mielone",
      ["Pyra"] = "ziemniak (regionalizm)",
      ["Półmisek"] = "naczynie do podawania potraw",
      ["Kwas"] = "napój fermentowany",
      ["Wino"] = "każdy napój alkoholowy",
      ["Zastawa"] = "komplet naczyń stołowych",
      ["Łyżka"] = "dawna miara lub narzędzie do jedzenia",
      ["Dziedziniec"] = "podwórze w zamku lub pałacu",
      ["Izba"] = "pokój w domu",
      ["Komnata"] = "elegancki pokój w pałacu",
      ["Zamek"] = "forteca, warownia",
      ["Strych"] = "poddasze",
      ["Chłodnia"] = "piwnica",
      ["Sień"] = "przedsionek w domu",
      ["Ganek"] = "weranda",
      ["Podwórze"] = "dziedziniec",
      ["Strumień"] = "mała rzeka",
      ["Łąka"] = "polana, pastwisko",
      ["Gaj"] = "mały lasek",
      ["Puszcza"] = "duży las",
      ["Dąbrowa"] = "las dębowy",
      ["Topola"] = "drzewo liściaste",
      ["Brzoza"] = "drzewo liściaste",
      ["Rżysko"] = "resztki po żniwach",
      ["Zboże"] = "rośliny uprawne",
      ["Chwast"] = "niepożądana roślina",
      ["Jutrzenka"] = "świt",
      ["Południe"] = "godzina dwunasta / połowa dnia",
      ["Nocą"] = "w nocy",
      ["Zimorodek"] = "dawniej nazwa pewnej pory roku",
      ["Wieczerza"] = "późny posiłek wieczorny",
      ["Poranek"] = "wczesna część dnia",
      ["Wczora"] = "wczoraj",
      ["Przedwczoraj"] = "poprzedni dzień",
      ["Pojutrze"] = "dzień po jutrze",
      ["Rzewny"] = "płaczliwy, sentymentalny",
      ["Trwożliwy"] = "bojaźliwy, lękliwy",
      ["Łaskawy"] = "przychylny, uprzejmy",
      ["Pobożny"] = "religijny, bogobojny",
      ["Cnotliwy"] = "moralny, godny",
      ["Zuchwały"] = "odważny, niekiedy bezczelny",
      ["Skromny"] = "pokorny",
      ["Rozrzutny"] = "hojny",
      ["Próżny"] = "próżny, zadufany",
      ["Miłosierny"] = "współczujący",
      ["Brona"] = "narzędzie rolnicze do spulchniania ziemi",
      ["Wóz"] = "pojazd konny",
      ["Zaprzęg"] = "zespół zwierząt ciągnących wóz",
      ["Szkuta"] = "dawny rodzaj łodzi",
      ["Łódź"] = "mała jednostka pływająca",
      ["Kozioł"] = "konstrukcja pomocnicza do transportu drewna",
      ["Mostek"] = "mały most",
      ["Kładka"] = "drewniany mostek",
      ["Bryczka"] = "lekki wóz konny",
      ["Karoca"] = "luksusowy powóz",
      ["Słowia"] = "dawny płaszcz",
      ["Czamara"] = "rodzaj kurtki",
      ["Żupan"] = "długa szata szlachecka",
      ["Płaszcz"] = "dawny strój wierzchni",
      ["Trzewik"] = "rodzaj obuwia",
      ["Rękawice"] = "różne typy rękawic",
      ["Pas"] = "opaska lub pasek przy ubraniu",
      ["Szarfa"] = "ozdobna taśma",
      ["Diadem"] = "korona lub opaska na głowę",
      ["Korale"] = "biżuteria",
      ["Kusza"] = "broń miotająca strzały",
      ["Miecz"] = "broń biała",
      ["Tarcza"] = "ochrona w walce",
      ["Hełm"] = "nakrycie głowy ochronne",
      ["Zbroja"] = "ochrona ciała",
      ["Sztandar"] = "chorągiew",
      ["Batalia"] = "bitwa",
      ["Oręż"] = "broń",
      ["Szaniec"] = "fortyfikacja ziemna",
      ["Wojsko"] = "armia",
      ["Księga"] = "książka dawniej",
      ["Zwoje"] = "dawne dokumenty",
      ["Papirus"] = "materiał do pisania",
      ["Rys"] = "szkic",
      ["Miniatura"] = "malunek ozdobny w księdze",
      ["Kronika"] = "zapis wydarzeń historycznych",
      ["Wiersz"] = "poezja",
      ["Pieśń"] = "utwór muzyczny lub literacki",
      ["Scena"] = "miejsce występów teatralnych",
      ["Maskarada"] = "przedstawienie, bal kostiumowy",
      ["Kościół"] = "zgromadzenie wiernych",
      ["Kapłan"] = "duchowny",
      ["Modlitwa"] = "rozmowa z Bogiem",
      ["Ołtarz"] = "miejsce ofiar i mszy",
      ["Cierniem"] = "korona cierniowa Jezusa",
      ["Cnoty"] = "moralne zalety",
      ["Post"] = "powstrzymywanie się od jedzenia",
      ["Sakrament"] = "obrzęd religijny",
      ["Klasztor"] = "miejsce życia zakonnego",
      ["Pielgrzym"] = "osoba w podróży religijnej",
      ["Zorza"] = "światło o wschodzie lub zachodzie słońca",
      ["Błyskawica"] = "piorun",
      ["Piorun"] = "wyładowanie atmosferyczne",
      ["Mgła"] = "opad pary wodnej",
      ["Rosa"] = "poranna woda na roślinach",
      ["Śnieżek"] = "drobny śnieg",
      ["Wiatr"] = "dawniej określenie siły wiatru",
      ["Chmura"] = "obłok",
      ["Burza"] = "gwałtowna pogoda",
      ["Grad"] = "opad lodu",
      ["Półka"] = "miejsce do odkładania przedmiotów",
      ["Skrzynia"] = "pojemnik na rzeczy",
      ["Piec"] = "urządzenie do ogrzewania",
      ["Stół"] = "mebel do jedzenia",
      ["Krzesło"] = "mebel do siedzenia",
      ["Łóżko"] = "miejsce do spania",
      ["Lampa"] = "źródło światła",
      ["Dzban"] = "naczynie do płynów",
      ["Kubek"] = "naczynie do picia",
      ["Talerz"] = "naczynie do jedzenia",
      ["Przepastny"] = "ogromny, rozległy",
      ["Szelest"] = "cichy dźwięk",
      ["Łaskotać"] = "drażnić dotykiem",
      ["Zbrukać"] = "pobrudzić",
      ["Zasłyszeć"] = "usłyszeć przypadkiem",
      ["Rozpaczliwy"] = "beznadziejny, desperacki",
      ["Skrzętny"] = "oszczędny, dokładny",
      ["Próżnować"] = "marnować czas",
      ["Niezadługo"] = "wkrótce",
      ["Zwątpić"] = "utracić wiarę",
      ["zwierzyna gruba"] = "dzik, jeleń, łoś",
      ["Zwierzyna drobna"] = "zając, bażant, kuropatwa",
      ["Zwierzyna płowa"] = "jelenie, sarny, daniele",
      ["Zwierzyna drapieżna"] = "lis, wilk, kuna",
      ["Zwierzyna ptasia"] = "kaczki, gęsi, bażanty, kuropatwy",
      ["Polowanie indywidualne"] = "wykonywane przez jednego myśliwego, samodzielnie tropiącego i pozyskującego zwierzynę.",
      ["Polowanie zbiorowe"] = "odbywa się w grupie, zorganizowane przez koło łowieckie, często z udziałem naganki.",
      ["Pędzenie zwierzyny"] = "technika polegająca na wypłoszeniu zwierząt z ukrycia w kierunku myśliwych.",
      ["Podchody"] = "ciche zbliżanie się do zwierzyny w celu jej obserwacji lub pozyskania.",
      ["Łowiectwo pasywne"] = "myśliwy oczekuje na zwierzynę w wyznaczonym miejscu (np. ambonie).",
      ["Łowiectwo aktywne"] = "myśliwy aktywnie tropi i podchodzi zwierzynę.",
      ["Strzelnica myśliwska"] = "miejsce do ćwiczeń strzeleckich dla myśliwych.",
      ["Przewodnik myśliwski"] = "osoba towarzysząca myśliwemu, znająca teren i zwyczaje zwierzyny.",
      ["Łowisko"] = "obszar, na którym prowadzi się gospodarkę łowiecką.",
      ["Obwód łowiecki"] = "jednostka organizacyjna łowiectwa, wydzielony teren przypisany kołu łowieckiemu.",
      ["Kołek graniczny"] = "oznaczenie granicy obwodu łowieckiego.",
      ["Droga zwierzyny"] = "regularnie uczęszczany szlak migracyjny zwierząt.",
      ["Trop / podchód"] = "ślady pozostawione przez zwierzynę; podchód to także technika zbliżania się do niej.",
      ["Gody / rykowisko"] = "okres rozrodczy zwierzyny, np. rykowisko jeleni.",
      ["Dymorfizm płciowy"] = "różnice w wyglądzie samca i samicy danego gatunku.",
      ["Sezon lęgowy"] = "czas, w którym zwierzyna rozmnaża się i wychowuje młode.",
      ["Migracje zwierzyny"] = "przemieszczanie się zwierząt w poszukiwaniu pożywienia lub schronienia.",
      ["Odsadzenie"] = "oddzielenie młodych od matki w hodowli.",
      ["Trofeum"] = "część zwierzyny (np. poroże), zachowywana jako pamiątka lub nagroda.",
      ["Dziczyzna"] = "mięso pozyskane ze zwierzyny łownej.",
      ["Oprawianie zwierzyny"] = "przygotowanie tuszy do spożycia (patroszenie, porcjowanie).",
      ["Wędzenie i suszenie mięsa"] = "tradycyjne metody konserwacji dziczyzny.",
      ["Skórowanie"] = "zdejmowanie skóry ze zwierzyny.",
      ["Myśliwy"] = "osoba posiadająca uprawnienia do wykonywania polowania.",
      ["Koło łowieckie"] = "lokalna organizacja zrzeszająca myśliwych, zarządzająca obwodem łowieckim.",
      ["Sezon łowiecki"] = "okres, w którym dozwolone jest polowanie na określone gatunki.",
      ["Pozwolenie łowieckie"] = "dokument uprawniający do wykonywania polowania.",
      ["Regulacja populacji"] = "działania mające na celu utrzymanie równowagi liczebnej zwierzyny.",
      ["Ochrona zwierzyny"] = "działania mające na celu zachowanie zdrowych populacji i środowiska.",
      ["Dzik"] = "Samiec: Odyniec, Samica: Locha, Młode: Warchlak",
      ["Jeleń szlachetny"] = "Samiec: Byk, Samica: Łania, Młode: Cielę",
      ["Jeleń sika"] = "Samiec: Byk, Samica: Łania, Młode: Cielę",
      ["Łoś"] = "Samiec: Byk, Samica: Łania, Młode: Cielę",
      ["Sarna"] = "Samiec: Kozioł, Samica: Koza, Młode: Koźlę",
      ["Zając szarak"] = "Samiec: Zając, Samica: Zającica, Młode: Zające",
      ["Bóbr"] = "Samiec: Bóbr, Samica: Bobrzyca, Młode: Młode bobry",
      ["Blaze a trail"] = "przetrzyj szlaki to metafora odnosząca się do pionierskiego działania, dokonywania czegoś po raz pierwszy, np. tworzenia nowej trasy, odkrywania czegoś lub inicjowania nowego trendu",
      ["Aberracja "] = "To odchylenie od normy lub zasady",
      ["To co naturalne, nie może być złe"] = "Chęć podążania człowieka za swoją naturą nie może być zła"
    };

  }
}
 